name: "free-disk-space"
description: "free disk space"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "Disk usage before cleanup:"
        df -h
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        echo "Disk usage after cleanup:"
        df -h
